wandb_version: 1

optimizer type:
  desc: null
  value: torch.optim.sgd.SGD
loss type:
  desc: null
  value: torch.nn.modules.loss.NLLLoss
learning_rate:
  desc: null
  value: 0.002
model:
  desc: null
  value: v3 batch norm l-tags-precalc color
training datasets:
  desc: null
  value: "[['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random2.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random3.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random6.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random14.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random15.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random9.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random11.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random15.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random6.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random5.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random13.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random14.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random11.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random13.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random5.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random12.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random7.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random2.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random15.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random7.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random4.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random12.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random9.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random6.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random15.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random3.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random7.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random13.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random4.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random10.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random5.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random5.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random11.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random7.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random4.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random8.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random4.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random10.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random10.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random5.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random14.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random10.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random14.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random8.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random13.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random3.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random4.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random12.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random2.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random12.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random8.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random7.npz']\n\
    \ ['/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random14.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random8.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random10.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random9.npz'\n\
    \  '/media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random12.npz']]"
validation datasets:
  desc: null
  value:
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random3.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random11.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random9.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random6.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random9.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random13.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random2.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random2.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random15.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random11.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random8.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random3.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random6.npz
epochs:
  desc: null
  value: 32
crossval fold:
  desc: null
  value: 3
total folds:
  desc: null
  value: 5
pixel reduction factor:
  desc: null
  value: 2
start time and date:
  desc: null
  value: 07.17.23_16:52:52
scheduler type:
  desc: null
  value: torch.optim.lr_scheduler.ExponentialLR
clip model:
  desc: null
  value: ViT-B/32
language prompts:
  desc: null
  value: /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/simple_nlp_prompts.npz
scheduler gamma:
  desc: null
  value: 0.9
NLL weights:
  desc: null
  value:
  - 0.10000000149011612
  - 1.0
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689726511.591986
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 5
