wandb_version: 1

optimizer type:
  desc: null
  value: torch.optim.sgd.SGD
loss type:
  desc: null
  value: torch.nn.modules.loss.NLLLoss
learning_rate:
  desc: null
  value: 0.002
model:
  desc: null
  value: v3 batch norm color 2
training datasets:
  desc: null
  value:
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random11.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random13.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random4.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random12.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random6.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random5.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random3.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random14.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random9.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random8.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random2.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random7.npz
validation datasets:
  desc: null
  value:
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random15.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/cube_dataset/grasp_cube_semi_random10.npz
epochs:
  desc: null
  value: 160
crossval fold:
  desc: null
  value: 4
total folds:
  desc: null
  value: 5
pixel reduction factor:
  desc: null
  value: 2
start time and date:
  desc: null
  value: 07.21.23_21:17:40
scheduler type:
  desc: null
  value: torch.optim.lr_scheduler.ExponentialLR
scheduler gamma:
  desc: null
  value: 0.9
NLL weights:
  desc: null
  value:
  - 0.10000000149011612
  - 1.0
cnn path:
  desc: null
  value: /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/results_run_07.19.23_20:44:38/v3
    batch norm color_best_model_fold_0
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690302593.361438
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 5
