wandb_version: 1

optimizer type:
  desc: null
  value: torch.optim.sgd.SGD
loss type:
  desc: null
  value: torch.nn.modules.loss.NLLLoss
learning_rate:
  desc: null
  value: 0.002
model:
  desc: null
  value: v3 batch norm l-tags color
training datasets:
  desc: null
  value:
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random5.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random12.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random7.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random2.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random15.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random7.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random4.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random12.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random9.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random6.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random15.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random3.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random7.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random13.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random4.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random10.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random5.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random5.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random11.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random7.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random4.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random8.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random4.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random10.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random10.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random5.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random14.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random10.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random14.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random3.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random9.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random9.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random2.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random8.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random11.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random13.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random15.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random3.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random6.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random2.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random11.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random6.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random8.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random13.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random3.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random4.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random12.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random2.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random12.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random8.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random7.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random14.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random8.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random10.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random9.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random12.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random2.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random9.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_ico_sphere_semi_random13.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random3.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random11.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cube_semi_random14.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random6.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random15.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_block_semi_random11.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random14.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random6.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder_semi_random13.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random15.npz
  - /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/mixed_object_dataset/grasp_cylinder2_semi_random5.npz
validation datasets:
  desc: null
  value: null
epochs:
  desc: null
  value: 20
crossval fold:
  desc: null
  value: 0
total folds:
  desc: null
  value: 5
pixel reduction factor:
  desc: null
  value: 2
start time and date:
  desc: null
  value: 07.31.23_20:06:05
scheduler type:
  desc: null
  value: torch.optim.lr_scheduler.ExponentialLR
clip model:
  desc: null
  value: ViT-L/14
language prompts:
  desc: null
  value: /media/jan-malte/17d1286b-1125-41e3-bf20-59faed637169/jan-malte/nlp-cls/simple_nlp_use_dataset.npz
scheduler gamma:
  desc: null
  value: 0.9
NLL weights:
  desc: null
  value:
  - 0.10000000149011612
  - 0.8999999761581421
nlp classifier:
  desc: null
  value: nlp cls v2
dataset name:
  desc: null
  value: mixed dataset
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690848377.340322
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 5
